[package]
name = "crosshair"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.34.0"
glium_shapes = "0.2.0"
glutin = "0.31.3"
glutin-winit = "0.4.2"
tray-icon = "0.11.3"
winit = "0.29.11"
